### ISSUE TITLE
Readme is misleading

### ISSUE THREAD

**Issue by mrd0ll4r** [walokra/markdown-page-generator-plugin#20]
Hey, thanks for the plugin!

The README.md has two issues:
- the dependency information shown still uses version 0.8
- the variable replacement feature is not actually available in the "official" builds (the latest version one can get from the repos is 0.9, which does not include the replacement)

Took me some time to figure out why replacements did not work for me... could you maybe upload the 0.10 to the official repos? Using a snapshot version is not an option for me right now, unfortunately :/

**Comment by walokra** [comment]
Version 0.10 is now released and should be available from repos. Forgot to do that earlier, sorry about that.
