### ISSUE TITLE
Support for Maven properties aka resource filter

### ISSUE THREAD

**Issue by johanlindquist** [walokra/markdown-page-generator-plugin#21]
Hi,

Would be nice to have an option to filter the MD files before generating the HTML - e.g. properties from the project, environment, etc.

Looks like it could be done while you read the MD files?

Thanks,

Johan

**Comment by walokra** [comment]
That could be nice feature. Have to see if I find time for it or you can always make a pull request :)

**Comment by johanlindquist** [comment]
Indeed, looked at doing just that but haven't found the time yet. ;)

**Comment by johanlindquist** [comment]
@walokra Not sure if this is the direction you'd see the plugin go but with these changes, it uses the Resources plugin style of replacing properties (in the form of ${some.property}) with the values defined in the pom.xml (or elsewhere).

**Comment by walokra** [comment]
Thanks for the pull request. I think that the resources plugin style filtering suits nicely for the plugin.

**Comment by johanlindquist** [comment]
Great, thanks for mergin - any chance of an official release? :)

**Comment by walokra** [comment]
I'm planning to do a release in the coming weeks.

**Comment by johanlindquist** [comment]
+1 & thanks!

**Comment by johanlindquist** [comment]
hi @walokra - any chance for that release? :)

**Comment by walokra** [comment]
The 1.0.0 release of the plugin should be found on Maven Central (since 2017-01-28).

**Comment by johanlindquist** [comment]
Hi @walokra - my bad, it is indeed there - many thanks!
