### ISSUE TITLE
replace pegdown due to deprecation & end of life notice

### ISSUE THREAD

**Issue by marc-medley** [walokra/markdown-page-generator-plugin#24]
On 2016.12.14, [sirthias/pegdown](https://github.com/sirthias/pegdown/) posted a deprecation notice that "pegdown has reached its end of life."

The pegdown notice also gives reasons to consider [@vsch's](https://github.com/vsch) [flexmark-java](https://github.com/vsch/flexmark-java) as a replacement.

**Comment by walokra** [comment]
Yep, I noticed the deprecation and have to see about replacing it with flexmark-java in coming versions.

**Comment by marc-medley** [comment]
FYI: Vladimir does have flexmark-java into a fork of this project. See https://github.com/vsch/markdown-page-generator-plugin 

I have an example project where the generated HTML from `doxia-module-markdown`, `walokra/markdown-page-generator-plugin` and `vsch/markdown-page-generator-plugin` can be viewed side-by-side.
https://github.com/marc-medley/004.55.markdown-maven-plugin-eval

I find flexmark-java's capability to add class attributes to the generated HTML useful. (e.g. Bootstrap class attributes)

**Comment by walokra** [comment]
Thanks for the reference to the fork and eval project. Seems that the flexmark-java is suitable replacement and the work switching to it has already been done.

Pull requests are welcome but I'll see if I find time to do the switch myself :)

**Comment by uschindler** [comment]
Just FYI,
we used pegdown in Apache Lucene, too and the change from out Ant task (written in Groovy) to felxmark was quite simple: https://github.com/apache/lucene-solr/commit/707d7b91e8793b4bb017e132c8a206acf85885ab#diff-19368e03d39aad04e99c31652e9827d6

There is also a compatibility layer available to convert PegDown options to flexmark options, so your plugin options could be migrated. In fact you can also remove the parser timeout, as - in contrast to pegdown - flexmark has no state machine that blows up on certain markdown constructs.

**Comment by walokra** [comment]
Everything needed for using flexmark-java and some new features are already done in @vsch's fork but merging and making the needed changes is problematic as that fork doesn't seem to be MIT licensed (although it says so).

**Comment by uschindler** [comment]
What is the problem with the fork (some new source files missing headers or copypasted without adapting license in a conformant way)?

**Comment by walokra** [comment]
Classes like https://github.com/vsch/markdown-page-generator-plugin/blob/master/src/main/java/com/vladsch/flexmark/page/generator/plugin/FlexmarkLinkResolver.java and https://github.com/vsch/markdown-page-generator-plugin/blob/master/src/main/java/com/vladsch/flexmark/page/generator/plugin/PageGeneratorExtension.java are licensed as private property and not MIT as the license suggests. Haven't yet asked from the author what he means by that.

**Comment by walokra** [comment]
Pull request #25 by @vsch is now merged and I'll prepare a new release. Thanks for the great work by @vsch's and [flexmark-java](https://github.com/vsch/flexmark-java).
