### ISSUE TITLE
Plugin (Version 2.0.0) does not copy directories with / on windows

### ISSUE THREAD

**Issue by mesche** [walokra/markdown-page-generator-plugin#28]
Plugin-Version: 2.0.0
POM Plugin Configuration: <copyDirectories>test/images</copyDirectories>
Result: Works on Mac / Linux - but not on Windows
Hint: When I use \ instead of the / character it works on windows, but not on Mac / Linux

Please fix this problem
Thank you

**Comment by walokra** [comment]
The fix is provided by PR #26 and merged to master. The version containing it is now released as 2.0.1.
