### ISSUE TITLE
Code doesnt' preserve line breaks

### ISSUE THREAD

**Issue by Nessia** [walokra/markdown-page-generator-plugin#43]

**Comment by Nessia** [comment]
(Removing the \ at the beginning, I haven't found a way to represent it better) If I have this markdown code:
```
\```
<dependency>
    <groupId>groupid</groupId>
    <artifactId>artifactid</artifactId>
    <version>version</version>
</dependency>
\```
```

the html is rendered as:
`<code>&lt;dependency&gt; &lt;groupId&gt;groupid lt;/groupId&gt; &lt;artifactId&gt;artifactid lt;/artifactId&gt; &lt;version&gt;version lt;/version&gt; &lt;/dependency&gt;</code>`

Even if I add the CSS to show the line breaks:
```
code {
  display: block;
  white-space: pre-wrap   
}
```
The browser shows everything in one line as there are no like breaks.

**Comment by walokra** [comment]
See https://github.com/walokra/markdown-page-generator-plugin/pull/45 for an example of adding FENCED_CODE_BLOCKS configuration for the generator. The generator uses [PegdownOptionsAdapter](https://github.com/vsch/flexmark-java/blob/master/flexmark-profile-pegdown/src/main/java/com/vladsch/flexmark/profile/pegdown/PegdownOptionsAdapter.java) which by default doesn't render fenced code blocks as "code blocks" without the extension.
