### ISSUE TITLE
HTML filename issue

### ISSUE THREAD

**Issue by rudgal** [walokra/markdown-page-generator-plugin#44]
I faced the following issue with latest version 2.3.0:

Whenever I use a markdown file, which includes the character sequence _MD_ not only as the extension but also within the actual name, the generated filename of the HTML is wrong. It appears as if the string _MD_ within the filename is also replaced.
For example

- stammdaten.md --> stam.htmlaten.html
- fremdidentifikation --> fre.htmlidentifikation.html

**Comment by walokra** [comment]
Thanks for noticing the issue and sorry for late answer. There was a bug in replacing the file extension and I'll release a new version with the fix soon.
