### ISSUE TITLE
Maven Plugin Warnings

### ISSUE THREAD

**Issue by patrodyne** [walokra/markdown-page-generator-plugin#66]
Maven since versions 3.9.x and 4.x, introduced [Plugin Validation](https://maven.apache.org/guides/plugins/validation/index.html) in order to help Maven users and Maven Plugin developers discover issues with the plugins they use or maintain that may break in the future.

As of v2.4.0, the `markdown-page-generator-plugin` triggers these _Maven Plugin Validation_ warnings:

~~~
[WARNING]  * com.ruleoftech:markdown-page-generator-plugin:2.4.0
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin should declare Maven artifacts in `provided` scope.
               If the plugin already declares them in `provided` scope, 
               update the maven-plugin-plugin to latest version.
               Artifacts found with wrong scope:
                   [org.apache.maven:maven-plugin-api:3.8.1]
~~~

The fix is to declare the scope to be `provided` for the `maven-plugin-api` dependency.

**Comment by walokra** [comment]
Thanks for the information. I'll update the project pom.
